version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: transactionMSDB
    restart: always
    ports:
      - 5433:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: transactiondb
